/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

/**
 *
 * @author lukas
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKolokvijum = new javax.swing.JMenu();
        jMenuItemZ1 = new javax.swing.JMenuItem();
        jMenuItemZ2 = new javax.swing.JMenuItem();
        jMenuItemZ3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuKolokvijum.setText("KOLOKVIJUM");

        jMenuItemZ1.setText("Zadatak 1");
        jMenuItemZ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZ1ActionPerformed(evt);
            }
        });
        jMenuKolokvijum.add(jMenuItemZ1);

        jMenuItemZ2.setText("Zadatak 2");
        jMenuItemZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZ2ActionPerformed(evt);
            }
        });
        jMenuKolokvijum.add(jMenuItemZ2);

        jMenuItemZ3.setText("Zadatak 3");
        jMenuItemZ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZ3ActionPerformed(evt);
            }
        });
        jMenuKolokvijum.add(jMenuItemZ3);

        jMenuBar1.add(jMenuKolokvijum);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemZ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZ2ActionPerformed
        FormaZadatak2 forma = new FormaZadatak2();
        forma.setVisible(true);
    }//GEN-LAST:event_jMenuItemZ2ActionPerformed

    private void jMenuItemZ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZ1ActionPerformed
//        this.dispose();  nije receno da li da se glavna forma zatvori
        FormaZadatak1 forma= new FormaZadatak1();
        forma.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemZ1ActionPerformed

    private void jMenuItemZ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZ3ActionPerformed
        FormaZadatak3 forma = new FormaZadatak3(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_jMenuItemZ3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemZ1;
    private javax.swing.JMenuItem jMenuItemZ2;
    private javax.swing.JMenuItem jMenuItemZ3;
    private javax.swing.JMenu jMenuKolokvijum;
    // End of variables declaration//GEN-END:variables
}
